version: "3"
    
volumes:
  volume-postgres:
    
services:
  jsninjify-db:
    container_name: jsninjify-db
    image: postgres:12-alpine
    ports:
      - 5432:5432
    volumes:
      - volume-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: jsninjify
      POSTGRES_PASSWORD: ThisBePassword
      POSTGRES_DB: jsninjify
    
  jsninjify-api:
    build: .
    container_name: jsninjify-api
    depends_on:
      - jsninjify-db
    links:
      - jsninjify-db
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=jsninjify
      - DB_PASSWORD=ThisBePassword
      - DB_PORT=5432
      - DB_NAME=jsninjify
      - FLASK_DEBUG=1
      - FLASK_APP=jsninjify